"""
Project Configuration File
Auto-generated by Module 1 — do not edit paths manually unless the folder
structure changes.
"""

PROJECT_ROOT = "/content/drive/MyDrive/Agentic_LoadForecasting_Project"

# Data paths
RAW_DATA_DIR = PROJECT_ROOT + "/data/raw"
PROCESSED_DATA_DIR = PROJECT_ROOT + "/data/processed"
SEQUENCES_DIR = PROJECT_ROOT + "/data/sequences"

# Model paths
BASELINE_MODEL_DIR = PROJECT_ROOT + "/models/baseline"
CNN_LSTM_ATTENTION_DIR = PROJECT_ROOT + "/models/cnn_lstm_attention"
SCALERS_DIR = PROJECT_ROOT + "/models/saved_scalers"

# Output paths
PLOTS_DIR = PROJECT_ROOT + "/outputs/plots"
METRICS_DIR = PROJECT_ROOT + "/outputs/metrics"
LOGS_DIR = PROJECT_ROOT + "/outputs/logs"
ALERTS_DIR = PROJECT_ROOT + "/outputs/alerts"

# Agent and simulator paths
AGENTS_DIR = PROJECT_ROOT + "/agents"
SIMULATOR_DIR = PROJECT_ROOT + "/simulator"
DASHBOARD_DIR = PROJECT_ROOT + "/dashboard"
CONFIG_DIR = PROJECT_ROOT + "/config"
DOCS_DIR = PROJECT_ROOT + "/docs"

# Random seed for reproducibility across all modules
RANDOM_SEED = 42
